const soldProducts = [
    { name: "قرص گیاهی", id: 1, soldCount: 24, delivered: false, price: 95000 },
    { name: "چای سبز اورگانیک", id: 2, soldCount: 15, delivered: true, price: 50000 },
    { name: "عسل طبیعی", id: 3, soldCount: 30, delivered: true, price: 120000 },
    { name: "روغن آرگان", id: 4, soldCount: 10, delivered: false, price: 80000 },
    { name: "صابون گیاهی", id: 5, soldCount: 20, delivered: true, price: 30000 },
    { name: "کرم مرطوب کننده اورگانیک", id: 6, soldCount: 12, delivered: false, price: 70000 },
    { name: "دمنوش بابونه", id: 7, soldCount: 18, delivered: true, price: 40000 },
    { name: "شامپو گیاهی", id: 8, soldCount: 22, delivered: false, price: 60000 },
    { name: "قرص جینسینگ", id: 9, soldCount: 8, delivered: true, price: 90000 },
    { name: "روغن نارگیل", id: 10, soldCount: 25, delivered: true, price: 75000 },
    { name: "مکمل گیاهی", id: 11, soldCount: 14, delivered: false, price: 85000 },
    { name: "عصاره آلوئه ورا", id: 12, soldCount: 17, delivered: true, price: 55000 },
    { name: "چای سیاه اورگانیک", id: 13, soldCount: 19, delivered: false, price: 45000 },
    { name: "کپسول ویتامین گیاهی", id: 14, soldCount: 11, delivered: true, price: 95000 },
    { name: "روغن زیتون خالص", id: 15, soldCount: 28, delivered: true, price: 100000 },
    { name: "صابون زغال فعال", id: 16, soldCount: 13, delivered: false, price: 35000 },
    { name: "دمنوش نعنا", id: 17, soldCount: 16, delivered: true, price: 40000 },
    { name: "قرص گیاهی خواب آور", id: 18, soldCount: 9, delivered: false, price: 65000 },
    { name: "روغن جوجوبا", id: 19, soldCount: 21, delivered: true, price: 90000 },
    { name: "کرم ضد آفتاب گیاهی", id: 20, soldCount: 7, delivered: false, price: 60000 },
    { name: "عصاره رزماری", id: 21, soldCount: 23, delivered: true, price: 50000 },
    { name: "چای سفید اورگانیک", id: 22, soldCount: 10, delivered: false, price: 55000 },
    { name: "ماسک صورت گیاهی", id: 23, soldCount: 18, delivered: true, price: 70000 },
    { name: "قرص گیاهی انرژی زا", id: 24, soldCount: 14, delivered: false, price: 80000 },
    { name: "روغن بادام شیرین", id: 25, soldCount: 20, delivered: true, price: 85000 }
  ];